package me.coley.recaf.ui.control.hex.clazz;

/**
 * Offset type to differentiate handling of {@link ClassOffsetInfo} values.
 *
 * @author Matt Coley
 */
public enum ClassOffsetInfoType {
	//// Top level
	MAGIC,
	MINOR_VERSION,
	MAJOR_VERSION,
	CONSTANT_POOL_COUNT,
	CONSTANT_POOL,
	CP_INFO,
	ACCESS_FLAGS,
	THIS_CLASS,
	SUPER_CLASS,
	INTERFACES_COUNT,
	INTERFACE,
	FIELDS_COUNT,
	FIELD_INFO,
	METHODS_COUNT,
	METHOD_INFO,
	ATTRIBUTES_COUNT,
	CLASS_ATTRIBUTES,
	//// Constant pool
	CP_UTF8,
	CP_INTEGER,
	CP_FLOAT,
	CP_LONG,
	CP_DOUBLE,
	CP_CLASS,
	CP_STRING,
	CP_FIELD_REF,
	CP_METHOD_REF,
	CP_INTERFACE_METHOD_REF,
	CP_NAME_TYPE,
	CP_METHOD_HANDLE,
	CP_METHOD_TYPE,
	CP_DYNAMIC,
	CP_INVOKE_DYNAMIC,
	CP_MODULE,
	CP_PACKAGE,
	//// Field
	FIELD_ACC_FLAGS,
	FIELD_NAME_INDEX,
	FIELD_DESC_INDEX,
	FIELD_ATTRIBUTES_COUNT,
	FIELD_ATTRIBUTES,
	//// Method
	METHOD_ACC_FLAGS,
	METHOD_NAME_INDEX,
	METHOD_DESC_INDEX,
	METHOD_ATTRIBUTES_COUNT,
	METHOD_ATTRIBUTES,
	//// Attribute
	ATTRIBUTE,
	ATTRIBUTE_NAME_INDEX,
	ATTRIBUTE_LENGTH,
	ATTRIBUTE_DATA,
	// Code
	CODE_MAX_STACK,
	CODE_MAX_LOCALS,
	CODE_LENGTH,
	CODE_BYTECODE,
	CODE_EXCEPTIONS_TABLE_LENGTH,
	CODE_EXCEPTION,
	// Constant value
	CONSTANT_VALUE_INDEX
}
