package me.coley.recaf.code;

public enum ClassSourceType {
    PHANTOM_GENERATED,      // Class was generated by JPhantom
    PRIMARY,                // Class came from disk
    LIBRARY,                // Class is a library
    INTERNAL_LIBRARY,       // Class is an internal library
}
