package me.coley.recaf.code;

/**
 * Describes the class source type.
 *
 * @author yapht
 */
public enum ClassSourceType {
    PHANTOM_GENERATED,      // Class was generated by JPhantom
    PRIMARY,                // Class came from disk
    LIBRARY,                // Class is a library
    INTERNAL_LIBRARY,       // Class is an internal library
}
