package me.coley.recaf.assemble;

/**
 * Describes a problem that occurred with generated bytecode.
 *
 * @author Matt Coley
 */
public class BytecodeException extends Exception {
	// TODO: Flesh out
}
