package me.coley.recaf.assemble;

/**
 * Describes a problem that occurred with generated bytecode.
 *
 * @author Matt Coley
 */
public class BytecodeException extends Exception {
	// TODO: Flesh out


	/**
	 * @return Line of problem.
	 */
	public int getLine() {
		// TODO: Flesh out
		return 0;
	}
}
