package software.coley.recaf.services.phantom.analysis;

import jakarta.annotation.Nonnull;
import jakarta.annotation.Nullable;
import org.objectweb.asm.AnnotationVisitor;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;
import org.objectweb.asm.Type;
import software.coley.recaf.services.phantom.model.PhantomClassConstraint;
import software.coley.recaf.services.phantom.model.PhantomFieldRequirement;
import software.coley.recaf.services.phantom.model.PhantomInnerRequirement;
import software.coley.recaf.services.phantom.model.PhantomMethodRequirement;
import software.coley.recaf.util.Types;

import java.util.Map;

/**
 * Emitter for resolved phantom classes.
 *
 * @author Matt Coley
 */
public class PhantomClassWriter {
	private static final String GENERATED_MARKER_DESC = "LAutoGenerated;";
	private static final String GENERATED_MARKER_MESSAGE = "Recaf automatically generated this class";
	private static final String RETENTION_DESC = "Ljava/lang/annotation/Retention;";
	private static final String RETENTION_POLICY_DESC = "Ljava/lang/annotation/RetentionPolicy;";

	private PhantomClassWriter() {}

	/**
	 * @param constraint
	 * 		Resolved class constraint.
	 * @param constraints
	 * 		All resolved constraints, used for nested-class metadata.
	 *
	 * @return Generated class bytes.
	 */
	@Nonnull
	public static byte[] write(@Nonnull PhantomClassConstraint constraint,
	                           @Nonnull Map<String, PhantomClassConstraint> constraints) {
		boolean isAnnotation = constraint.isAnnotation();
		boolean isInterface = constraint.isInterface();
		int access = Opcodes.ACC_PUBLIC;
		if (isInterface)
			access |= Opcodes.ACC_INTERFACE | Opcodes.ACC_ABSTRACT;
		if (isAnnotation)
			access |= Opcodes.ACC_ANNOTATION;

		int version = Opcodes.V1_8;
		ClassWriter writer = new ClassWriter(0);
		String[] interfaces = constraint.getResolvedInterfaces().isEmpty() ?
				null : constraint.getResolvedInterfaces().toArray(String[]::new);
		writer.visit(version, access, constraint.getName(), null, constraint.getResolvedSuperName(), interfaces);

		// Mark generated phantoms so other tooling can recognize synthetic placeholders.
		AnnotationVisitor marker = writer.visitAnnotation(GENERATED_MARKER_DESC, true);
		marker.visit("msg", GENERATED_MARKER_MESSAGE);
		marker.visitEnd();

		// Synthetic annotation phantoms need a retention policy to compile source usage correctly.
		if (isAnnotation) {
			AnnotationVisitor retention = writer.visitAnnotation(RETENTION_DESC, true);
			retention.visitEnum("value", RETENTION_POLICY_DESC,
					constraint.hasRuntimeVisibleAnnotationEvidence() ? "RUNTIME" : "CLASS");
			retention.visitEnd();
		}

		if (constraint.getOuterName() != null) {
			writer.visitInnerClass(constraint.getName(), constraint.getOuterName(), constraint.getInnerSimpleName(),
					innerClassAccess(constraint));
		}
		for (PhantomInnerRequirement inner : constraint.getDeclaredInners()) {
			writer.visitInnerClass(inner.innerName(), constraint.getName(), inner.innerSimpleName(),
					innerClassAccess(constraints.get(inner.innerName())));
		}

		for (PhantomFieldRequirement field : constraint.getFieldRequirements()) {
			int fieldAccess = Opcodes.ACC_PUBLIC;
			if (isInterface || field.isStatic())
				fieldAccess |= Opcodes.ACC_STATIC;
			if (isInterface)
				fieldAccess |= Opcodes.ACC_FINAL;
			writer.visitField(fieldAccess, field.getName(), field.getDescriptor(), null, null).visitEnd();
		}

		if (!isInterface) {
			writeConstructor(writer, constraint.getResolvedSuperName(), "()V");
			for (PhantomMethodRequirement method : constraint.getMethodRequirements()) {
				if (method.isConstructor() && !"()V".equals(method.getDescriptor()))
					writeConstructor(writer, constraint.getResolvedSuperName(), method.getDescriptor());
			}
		}

		for (PhantomMethodRequirement method : constraint.getMethodRequirements()) {
			if (method.isConstructor())
				continue;
			writeMethod(writer, method, isInterface);
		}

		writer.visitEnd();
		return writer.toByteArray();
	}

	private static int innerClassAccess(@Nullable PhantomClassConstraint constraint) {
		int access = Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC;
		if (constraint == null)
			return access;
		if (constraint.isInterface())
			access |= Opcodes.ACC_INTERFACE | Opcodes.ACC_ABSTRACT;
		if (constraint.isAnnotation())
			access |= Opcodes.ACC_ANNOTATION;
		return access;
	}

	private static void writeConstructor(@Nonnull ClassWriter writer, @Nonnull String superName, @Nonnull String descriptor) {
		MethodVisitor visitor = writer.visitMethod(Opcodes.ACC_PUBLIC, "<init>", descriptor, null, null);
		visitor.visitCode();
		visitor.visitVarInsn(Opcodes.ALOAD, 0);
		visitor.visitMethodInsn(Opcodes.INVOKESPECIAL, superName, "<init>", "()V", false);
		visitor.visitInsn(Opcodes.RETURN);
		visitor.visitMaxs(1, localSize(descriptor, false));
		visitor.visitEnd();
	}

	private static void writeMethod(@Nonnull ClassWriter writer,
	                                @Nonnull PhantomMethodRequirement method,
	                                boolean ownerIsInterface) {
		boolean isAbstract = ownerIsInterface && !method.isStatic();
		int access = Opcodes.ACC_PUBLIC;
		if (method.isStatic())
			access |= Opcodes.ACC_STATIC;
		if (isAbstract)
			access |= Opcodes.ACC_ABSTRACT;

		MethodVisitor visitor = writer.visitMethod(access, method.getName(), method.getDescriptor(), null, null);
		if (isAbstract) {
			visitor.visitEnd();
			return;
		}

		// Stub out the method body based on the return type.
		visitor.visitCode();
		Type returnType = Type.getReturnType(method.getDescriptor());
		switch (returnType.getSort()) {
			case Type.VOID -> {
				visitor.visitInsn(Opcodes.RETURN);
				visitor.visitMaxs(0, localSize(method.getDescriptor(), method.isStatic()));
			}
			case Type.BOOLEAN, Type.BYTE, Type.CHAR, Type.SHORT, Type.INT -> {
				visitor.visitInsn(Opcodes.ICONST_0);
				visitor.visitInsn(Opcodes.IRETURN);
				visitor.visitMaxs(1, localSize(method.getDescriptor(), method.isStatic()));
			}
			case Type.LONG -> {
				visitor.visitInsn(Opcodes.LCONST_0);
				visitor.visitInsn(Opcodes.LRETURN);
				visitor.visitMaxs(2, localSize(method.getDescriptor(), method.isStatic()));
			}
			case Type.FLOAT -> {
				visitor.visitInsn(Opcodes.FCONST_0);
				visitor.visitInsn(Opcodes.FRETURN);
				visitor.visitMaxs(1, localSize(method.getDescriptor(), method.isStatic()));
			}
			case Type.DOUBLE -> {
				visitor.visitInsn(Opcodes.DCONST_0);
				visitor.visitInsn(Opcodes.DRETURN);
				visitor.visitMaxs(2, localSize(method.getDescriptor(), method.isStatic()));
			}
			default -> {
				visitor.visitInsn(Opcodes.ACONST_NULL);
				visitor.visitInsn(Opcodes.ARETURN);
				visitor.visitMaxs(1, localSize(method.getDescriptor(), method.isStatic()));
			}
		}
		visitor.visitEnd();
	}

	private static int localSize(@Nonnull String descriptor, boolean isStatic) {
		return (isStatic ? 0 : 1) + Types.countParameterSlots(Type.getMethodType(descriptor));
	}
}
